AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SurveyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: SurveyLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-0261755bbcb8c4a84
        InstanceType: t2.micro
        SecurityGroupIds:
          - !ImportValue AppInstanceSecurityGroupID
          - !ImportValue ALBsecurityGroupID
          - !ImportValue RDSSecurityGroupID 
          - !ImportValue EFSMountTargetSecurityGroupID
        UserData: !Base64 |
          #!/bin/bash
          sudo apt update -y
          cd /home
          sudo git clone https://github.com/PHIDELIST/survey-and-feedback-application.git
          cd survey-and-feedback-application/backend-node-js
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install --lts
          npm install -g npm@9.7.2
          sudo chown -R ubuntu:ubuntu /home/survey-and-feedback-application/backend-node-js
          npm install bcrypt cors mssql jsonwebtoken
          node server.js
          
          

        
  SurveyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref SurveyLaunchTemplate
        Version: !GetAtt SurveyLaunchTemplate.LatestVersionNumber # Specify the same version as in the Launch Template
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - !ImportValue AppSubnet1
        - !ImportValue AppSubnet2
      TargetGroupARNs: !ImportValue BackendTGArn
      Tags:
        - Key: Name
          Value: SurveyAutoScalingGroup
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: The name of the Auto Scaling Group
    Value: !Ref SurveyAutoScalingGroup
    Export:
      Name: AutoScalingGroupName
