AWSTemplateFormatVersion: 2010-09-09
Description: |
  The primary MSSQL RDS Database with a read replica for the application
  - RDS Instance
  - Database Security Group
  - DBSubnetGroup

Parameters:
  BackupRetentionPeriod:
    Type: Number
    Default: 7
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
  DBInstanceIdentifier:
    Type: String
    Default: Survey-Instance
  DBName:
    Type: String
  
  DeletionProtection:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  EngineVersion:
    Type: String
    Default: '14.00.3460.9.v1'
  MasterUsername:
    Type: String
    Default: 'sa'
  MasterUserPassword:
    Type: String
    NoEcho: true
    Default: 'rootpassword'

Resources:


  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      # LicenseModel: license-included
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      DBSubnetGroupName: !ImportValue DBSubnetGroup
      DeletionProtection: !Ref DeletionProtection
      EnablePerformanceInsights: false
      Engine: sqlserver-ex
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !ImportValue RDSSecurityGroupID
        - !ImportValue AppInstanceSecurityGroupID

  ReadReplica:
    Type: AWS::RDS::DBInstance
    DependsOn: Database
    Properties:
      SourceDBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceIdentifier: !Sub ${DBInstanceIdentifier}-readreplica
      DBInstanceClass: !Ref DBInstanceClass
      AvailabilityZone: !Select [1, !GetAZs ""]
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !ImportValue RDSSecurityGroupID

